### PR TITLE
Profile improvements.

### PR DESCRIPTION
**Pull request by spier**
Please compare [current profile](https://github.com/meltwater/.github/tree/main/profile) to [proposal](https://github.com/meltwater/.github/blob/profile-proposal/profile).

Changes:

- changed layout  of header image. removed link.
- removed values section (those are listed in all job postings as well)
- broke up text into two blocks by adding a headline in between
- broke up the last sentence about jobs+blog into two
- added white background to the social media icons to make them visible in dark theme (now PNGs instead of SVGs). Thanks @ollieparsley !

### CODE REVIEW

**Comment by spier** [comment]
This version of the image works ok-ish now.
Turns out one cannot just change the CSS `style` of an image as freely as I thought.

So instead I created a new PNG version of the image and added rounded corners manually, to get the effect that I was shooting for.

TODO:

* not sure if I cut out the image exactly in the center?
* remove the JPG (unless we want to use it for something else?)
* (unrelated) make the social media icon visible when in dark mode

**Comment by spier** [comment]
More details about the bug with the invisible icons in dark mode:
Screenshot 2021-10-19 at 16 05 02

**Review by ollieparsley — APPROVED** [review]
Looks good to me. Nice to see us iterating on the original design :)

**Review by recollir — APPROVED** [review]

**Review by terodox — APPROVED** [review]
I like the updates

**Pull request merged**
